spring.application.name=greeting-service
server.port=8080

greeting-service.greeting=Ola
greeting-service.default-name=Mundo
spring.profiles.active=fr
spring.config.import=optional:configserver:http://localhost:8888/

# Self Registration Pattern
eureka.client.service-url.default-zone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.client.healthcheck.enabled=true

# Health Check e Monitoramento Actuator
management.endpoints.web.exposure.include=health,info,metrics,circuit-breakers,circuit-breaker-events
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.defaults.enabled=true

# Informações do Endpoint /actuator/info
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=Microservice Java 2026
info.app.autor=Leonardo Manfroi Zancanaro

# Metadata no Eureka
eureka.instance.metadata-map.github.repo=Leo981-web/microservices-java