spring.application.name=config-service
server.port=8888

#spring.profiles.active=native

#Spring.cloud.config.server.native.search-locations=classpath:/configs/{application}

spring.cloud.config.server.git.uri=https://github.com/Leo981-web/microservices-java.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.search-paths=/configs/{application}

#spring.cloud.config.server.git.username=leonardo-manfroi

# Self Registration Pattern
eureka.client.service-url.default-zone=http://localhost:8761/eureka
# Ideal para ambiente de containers
eureka.instance.prefer-ip-address=true
# Personalizar o Id de cada instância
eureka.instance.instance-id=${spring.application.name}:${server.port}
#indicar que o serviço de registro deve validar a saude do serviço atraves do actuator, e não somente Heartbeat
# opcional pois o valor padrão e true
eureka.client.healthcheck.enabled=true

management.endpoints.web.exposure.include=health,info,metrics
#exibir todas as informações de saude
management.endpoint.health.show-details=always
#exibir informações no endpoint /actuator/info
management.info.env.enabled=true

#Personalização de informaçoes no / info

info.app.name=${spring.application.name}
info.app.description=Microservice Java 2026
info.app.autor=Leonardo Manfroi Zancanaro

#personalização de mata dados
eureka.instance.metadata-map.gihub.repo=Leo981-web/microservices-java

#definir a utilização dos Probres
#opcional pois o padrão e true
management.endpoint.health.probes.enabled=true
management.health.defaults.enabled=true

